alias open_aliases='open ~/.bash_profile'
alias open_mm='open ~/mm.cfg'
alias cd_data='cd /Volumes/Data/'
alias cd_os='cd /Volumes/OS/'
alias cd_bin='cd /Volumes/Data/bin'
alias flashlog='tail -f "/Users/farrh009/Library/Preferences/Macromedia/Flash Player/Logs/flashlog.txt"'
alias ll='ls -al'
alias hl='haxelib'
# alias vim=/usr/local/Cellar/macvim/7.4-76/MacVim.app/Contents/MacOS/Vim
alias vim=nvim
alias nw=/Applications/nwjs/nwjs.app/Contents/MacOS/nwjs

#export LC_CTYPE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt:$PATH"
export PATH="$PATH:~/Library/Python/2.7/bin"
export PATH="$PATH:~/cpdev/scripts/bin"
export PATH="$PATH:~/.cargo/bin"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export EDITOR=/usr/local/Cellar/macvim/7.4-76/MacVim.app/Contents/MacOS/Vim
export P4CONFIG=.p4config
export HOMEBREW_GITHUB_API_TOKEN=f666454d00e0aef8fff4c89c4578bfb405980b55

# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

export JAVA_HOME=`/usr/libexec/java_home -v 1.7.0_79`
export ANDROID_NDK_ROOT=~/Library/Android/android-ndk-r10d
export ANDROID_SDK_ROOT=~/Library/Android/sdk
export UNITY_HOME=/Applications/Unity
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:~/bin:$ANDROID_SDK_ROOT/tools

# if [ -f $(brew --prefix)/etc/bash_completion ]; then
#     . $(brew --prefix)/etc/bash_completion
# else
# 	echo "Could not find the bash completion script."
# fi

source ~/.git-prompt.sh
source ~/.git-completion.sh

export CLICOLOR=1
export LSCOLORS=gxFxBxDxCxegedabagacad

function prompt
{
local WHITE="\[\033[1;37m\]"
local GREEN="\[\033[0;32m\]"
local CYAN="\[\033[0;36m\]"
local GRAY="\[\033[0;37m\]"
local BLUE="\[\033[0;94m\]"
export PS1="
${GREEN}\u${CYAN}@${BLUE}\h ${CYAN}\w"' $(__git_ps1 "(%s)") '"${GRAY}"
}
prompt

# Powerline Setup
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /Library/Python/2.7/site-packages/powerline/bindings/bash/powerline.sh

[ -s "/Users/farrh009/.dnx/dnvm/dnvm.sh" ] && . "/Users/farrh009/.dnx/dnvm/dnvm.sh" # Load dnvm

# FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
